# Generated by Django 5.1.5 on 2025-02-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0006_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_type',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='assessmentresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='assessmentresponse',
            name='user',
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapist.client')),
            ],
        ),
        migrations.DeleteModel(
            name='AssessmentType',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentQuestion',
        ),
        migrations.DeleteModel(
            name='AssessmentResponse',
        ),
    ]
